LDBR-3.6: Добавить Viper
go-park-mail-ru/2021_2_LadnoDavayteBezRoflov pull request #16
Opened 2021-11-22 22:57 UTC by Trollbump

2021-11-22 23:11 UTC, Trollbump commented
![](https://github.trello.services/images/mini-trello-icon.png) [Viper + config [3.6]](https://trello.com/c/M6ki3d9M/72-viper-config-36)

2021-11-23 10:19 UTC, TonyBlock reviewed
Похоже на правду, но есть пара замечаний:
- отступы скачут
- часть значений можно вынести в конфиг

Также есть вопрос/предложение. Вайпер же позволяет полностью считаться в структуру без прописывания Get для каждого параметра. Почему не был выбрал такой вариант?

2021-11-23 10:19 UTC, TonyBlock commented on cmd/api/config.yml
> +  card_lists_url: '/cardLists',
Почему другой отступ

2021-11-23 10:19 UTC, TonyBlock commented on cmd/api/settings.go
>  )
Что с отступами?

2021-11-23 10:19 UTC, TonyBlock commented on cmd/api/settings.go
> +	ServerAddress string `mapstructure:"server_address"`
Отступы

2021-11-23 10:19 UTC, TonyBlock commented on cmd/api/settings.go
> +	AllowedMethods []string `mapstructure:"allowed_methods"`
Почему разные отступы?

2021-11-23 10:19 UTC, TonyBlock commented on cmd/api/settings.go
> +	DefaultAvatarName string `mapstructure:"default_avatar_name"`
Почему разные отступы?

2021-11-23 10:19 UTC, TonyBlock commented on cmd/api/settings.go
> +    RedisPort     string
Почему разные отступы?

2021-11-23 10:19 UTC, TonyBlock commented on cmd/api/settings.go
> +            "http://localhost:8000",
Имеет смысл вынести это в конфиг

2021-11-23 10:19 UTC, TonyBlock commented on cmd/api/settings.go
> +    settings.corsConfig.AllowCredentials = true
Мб тоже в конфиг пихнуть

2021-11-23 12:20 UTC, DPeshkoff requested changes
плюсую все отступы

2021-11-23 12:20 UTC, DPeshkoff commented on cmd/api/config.yml
> +session_cookie_life_time_in_days: 72h
`life_time_in_days` -> `72h`

по названию дни, а в значении часах

2021-11-23 12:20 UTC, DPeshkoff commented on cmd/api/settings.go
> +            "http://localhost:8000",
Оно вынесено, просто не используется - `server_address`

2021-11-23 13:04 UTC, TonyBlock commented on cmd/api/config.yml
> +session_cookie_life_time_in_days: 72h
Да, в оригинале же там просто было 3, никаких 72h

2021-11-24 22:52 UTC, Trollbump commented on cmd/api/settings.go
>  )
все хорошо

2021-11-24 22:52 UTC, Trollbump commented on cmd/api/settings.go
> +	ServerAddress string `mapstructure:"server_address"`
fixed

2021-11-24 22:53 UTC, Trollbump commented on cmd/api/settings.go
> +	AllowedMethods []string `mapstructure:"allowed_methods"`
fixed

2021-11-24 22:53 UTC, Trollbump commented on cmd/api/settings.go
> +	DefaultAvatarName string `mapstructure:"default_avatar_name"`
fixed

2021-11-24 22:54 UTC, Trollbump commented on cmd/api/settings.go
> +    RedisPort     string
fixed

2021-11-24 23:21 UTC, Trollbump commented on cmd/api/config.yml
> +session_cookie_life_time_in_days: 72h
fixed

2021-11-24 23:23 UTC, Trollbump commented on cmd/api/config.yml
> +  card_lists_url: '/cardLists',
fixed

2021-11-24 23:27 UTC, DPeshkoff approved these changes

2021-11-24 23:29 UTC, TonyBlock approved these changes

2021-11-25 13:45 UTC, TonyBlock approved these changes

2021-11-25 13:46 UTC, merged